[logger]
; logging levels: debug | info | warning | error | critical
level = debug
path = 
max_bytes = 1e6
clear_on_start = 1
scpi_log = 1
scpi_log_path = 
save_failed_logs = 1
failed_logs_folder = 

[temperature]
room_temperature = 29

[ITC_1T1R]
Measure_temperature = False
BL_channel = 1
NL_channel = 2
Temperature_channel = 2
Gate_channel = 1
Arm_link_pin = 1
Trigger_link_pin = 2

[ITC_probe_station]
Measure_temperature = False
Memristor_channel = 1
Temperature_channel = 2